version: "3.9"
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: millarx
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: vehicle
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
  redis:
    image: redis:7
    restart: always
    ports: ["6379:6379"]
volumes:
  pgdata:
